### ISSUE TITLE
before.conf file: Are rule exclusions disabled by default from: Generic rule to disable plugin SecRule TX:wordpress-rule-exclusions-plugin_enabled "@eq 0" "id:9507099,phase:1,pass,nolog,ctl:ruleRemoveById=9507100-9507999

### ISSUE THREAD

**Issue by Danrancan** [coreruleset/wordpress-rule-exclusions-plugin#61] opened 2024-09-05 02:09 UTC
It is my understanding that this plugin comes automatically enabled, and you don't have to do anything except install the .conf files to the plugins directory.

However, looking at before.conf file, I see:
```
# Generic rule to disable plugin
SecRule TX:wordpress-rule-exclusions-plugin_enabled "@eq 0" "id:9507099,phase:1,pass,nolog,ctl:ruleRemoveById=9507100-9507999"
```

Im probably not interpreting this correctly, but since :wordpress-rule-exclusions-plugin_enabled = 0, doesn't that mean that the plugin is NOT enabled? To enable this plugin automatically, wouldn't you need this line instead?
```
# Generic rule to disable plugin
SecRule TX:wordpress-rule-exclusions-plugin_enabled "@eq 1" "id:9507099,phase:1,pass,nolog,ctl:ruleRemoveById=9507100-9507999"
```
Is there any way to test if my plugin is indeed working for sure?
I appreciate any clarification you can give me on this. I just want to be sure my plugin is working correctly.

**Comment by EsadCetiner** [comment] 2024-09-05 03:26
@Danrancan 

> Im probably not interpreting this correctly, but since :wordpress-rule-exclusions-plugin_enabled = 0, doesn't that mean that the plugin is NOT enabled? To enable this plugin automatically, wouldn't you need this line instead?

The rule is checking if ``TX:wordpress-rule-exclusions-plugin_enabled`` = 0, and if it's set to 0 then the plugin is disabled.

> Is there any way to test if my plugin is indeed working for sure?

Most plugins ship with tests [including the WordPress plugin](https://github.com/coreruleset/wordpress-rule-exclusions-plugin/tree/master/tests/regression/wordpress-rule-exclusions-plugin). You can always run the tests with go-ftw and see if the tests pass/fail. If all of the tests pass, then that means the plugin is correctly enabled, see here on how to [run tests with go-ftw](https://coreruleset.org/docs/development/testing/).

Note that this plugin is using an older test format so you must use [go-ftw version 0.6.4](https://github.com/coreruleset/go-ftw/releases/tag/v0.6.4).

**Comment by EsadCetiner** [comment] 2024-09-22 07:48
Closing this issue since this isn't related to reporting an issue with the plugin or a feature request.

**Closed by EsadCetiner** 2024-09-22 07:48 UTC
